// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250310094851_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99c00af1-2be2-4c83-a4a3-35f2ad326bb5"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(329),
                            Description = "Áo Ngắn Tay",
                            Name = "T-SHIRTS"
                        },
                        new
                        {
                            Id = new Guid("a12dd0e4-3ea2-42e8-bfbd-e2daba5b6931"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(334),
                            Description = "Quần",
                            Name = "PANTS"
                        },
                        new
                        {
                            Id = new Guid("a59e7340-2a4a-4384-8b9e-2264c462cdfa"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(337),
                            Description = "Áo khoác",
                            Name = "JACKETS"
                        },
                        new
                        {
                            Id = new Guid("719730c6-6e98-4300-a064-7c5673ce2f50"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(340),
                            Description = "Sweater",
                            Name = "HOODIES & SWEATSHIRTS"
                        },
                        new
                        {
                            Id = new Guid("84947687-13e1-40c8-8b6e-28f1ae4c8931"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(342),
                            Description = "Áo sơ mi",
                            Name = "SHIRT"
                        });
                });

            modelBuilder.Entity("api.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("api.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3086fccd-0a69-49f3-b228-b8b42d381539"),
                            LastUpdated = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(542),
                            ProductId = new Guid("1f1ee017-6d3a-46f8-839a-3b41330fbf17"),
                            Stock = 2000
                        },
                        new
                        {
                            Id = new Guid("1dabe982-87f3-4c3c-9336-e4ed83fe4f88"),
                            LastUpdated = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(550),
                            ProductId = new Guid("7a2f9e3b-8a15-4c0b-b784-693c0e20d8a9"),
                            Stock = 2000
                        },
                        new
                        {
                            Id = new Guid("dfec1b24-9d8e-44c2-a8a3-955a5c800c8b"),
                            LastUpdated = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(553),
                            ProductId = new Guid("a572cd2d-72e4-4e1a-b3cc-84121a9f7a4e"),
                            Stock = 2000
                        },
                        new
                        {
                            Id = new Guid("2bd3ef58-8159-4a63-bfe9-53a538104cc7"),
                            LastUpdated = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(555),
                            ProductId = new Guid("ec16787e-f650-4a7e-839e-f034b52f9273"),
                            Stock = 2000
                        },
                        new
                        {
                            Id = new Guid("a7b08cfb-37ff-449d-aee1-207900d212f3"),
                            LastUpdated = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(557),
                            ProductId = new Guid("b8b19bdc-d9e6-4d1a-a25d-7c528f47db69"),
                            Stock = 2000
                        },
                        new
                        {
                            Id = new Guid("20f7a0da-f1e8-457f-affa-3fac80ec6a25"),
                            LastUpdated = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(561),
                            ProductId = new Guid("a742f0bd-6f85-4e50-9bc3-8b77b3061c77"),
                            Stock = 2000
                        },
                        new
                        {
                            Id = new Guid("8ef43a2e-8d6b-459b-8d6a-5dd3ae601e9f"),
                            LastUpdated = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(563),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Stock = 2000
                        });
                });

            modelBuilder.Entity("api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotolPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("api.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProducId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f1ee017-6d3a-46f8-839a-3b41330fbf17"),
                            CategoryId = new Guid("99c00af1-2be2-4c83-a4a3-35f2ad326bb5"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(382),
                            Description = "Chiếc áo được làm từ chất liệu vải tổng hợp giúp người mặc cảm thấy thoải mái",
                            ImageUrl = "aophong.png",
                            Name = "Áo phông nam ngắn tay",
                            Price = 999000m,
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = new Guid("7a2f9e3b-8a15-4c0b-b784-693c0e20d8a9"),
                            CategoryId = new Guid("99c00af1-2be2-4c83-a4a3-35f2ad326bb5"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(400),
                            Description = "Chiếc áo được làm từ chất liệu vải tổng hợp giúp người mặc cảm thấy thoải mái",
                            ImageUrl = "aopolo.png",
                            Name = "Áo polo nam",
                            Price = 1999000m,
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = new Guid("a572cd2d-72e4-4e1a-b3cc-84121a9f7a4e"),
                            CategoryId = new Guid("719730c6-6e98-4300-a064-7c5673ce2f50"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(405),
                            Description = "Chiếc áo hoodie với form dáng oversize, chất liệu vải dày dặn",
                            ImageUrl = "aohoodie.png",
                            Name = "Áo hoodie",
                            Price = 299000m,
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = new Guid("ec16787e-f650-4a7e-839e-f034b52f9273"),
                            CategoryId = new Guid("a59e7340-2a4a-4384-8b9e-2264c462cdfa"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(408),
                            Description = "Chiếu áo này mặc vào là đẹp",
                            ImageUrl = "aokhoacgio.png",
                            Name = "Áo khoác gió 2 lớp",
                            Price = 599000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("b8b19bdc-d9e6-4d1a-a25d-7c528f47db69"),
                            CategoryId = new Guid("a12dd0e4-3ea2-42e8-bfbd-e2daba5b6931"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(411),
                            Description = "Quần jeans ống rộng phong cách Unisex",
                            ImageUrl = "quanjeans.png",
                            Name = "Quần jeans ống rộng",
                            Price = 599000m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = new Guid("a742f0bd-6f85-4e50-9bc3-8b77b3061c77"),
                            CategoryId = new Guid("a12dd0e4-3ea2-42e8-bfbd-e2daba5b6931"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(415),
                            Description = "Quần nỉ ống rộng phong cách Unisex",
                            ImageUrl = "quanni.png",
                            Name = "Quần nỉ ống rộng",
                            Price = 599000m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            CategoryId = new Guid("a12dd0e4-3ea2-42e8-bfbd-e2daba5b6931"),
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(417),
                            Description = "Quần short phong cách Unisex",
                            ImageUrl = "quanshort.png",
                            Name = "Quần short",
                            Price = 99000m,
                            StockQuantity = 500
                        });
                });

            modelBuilder.Entity("api.Models.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0671087-a8f4-4d64-8a5d-7d40572242f7"),
                            Color = "Đen",
                            ImageUrl = "",
                            Price = 99000m,
                            ProductId = new Guid("1f1ee017-6d3a-46f8-839a-3b41330fbf17"),
                            Size = "M",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("d3568a6a-a713-424d-b5a0-f277cc066cb6"),
                            Color = "Đen",
                            ImageUrl = "",
                            Price = 99000m,
                            ProductId = new Guid("1f1ee017-6d3a-46f8-839a-3b41330fbf17"),
                            Size = "L",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("ae58d05b-70f8-4a27-8d32-d9ccf322a5ea"),
                            Color = "Xanh",
                            ImageUrl = "",
                            Price = 99000m,
                            ProductId = new Guid("1f1ee017-6d3a-46f8-839a-3b41330fbf17"),
                            Size = "XXL",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("74b16dcb-996f-4e78-8022-f73895c71e23"),
                            Color = "Trắng",
                            ImageUrl = "",
                            Price = 99000m,
                            ProductId = new Guid("ec16787e-f650-4a7e-839e-f034b52f9273"),
                            Size = "L",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("e2427b94-5cbc-4522-b53a-3279b5906220"),
                            Color = "Trắng",
                            ImageUrl = "",
                            Price = 99000m,
                            Size = "XL",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("5b531801-cd30-4c7c-8977-b30a3bd14d83"),
                            Color = "Xanh",
                            ImageUrl = "",
                            Price = 99000m,
                            Size = "28",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("09ef2f23-4d04-44a3-95a0-2be4da81a54d"),
                            Color = "Đỏ",
                            ImageUrl = "",
                            Price = 99000m,
                            Size = "L",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("b259fcaa-e1f7-46f6-9310-b152694abdec"),
                            Color = "Trắng",
                            ImageUrl = "",
                            Price = 99000m,
                            Size = "L",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("b8b19bdc-d9e6-4d1a-a25d-7c528f47db69"),
                            Color = "Trắng",
                            ImageUrl = "",
                            Price = 99000m,
                            Size = "L",
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("a572cd2d-72e4-4e1a-b3cc-84121a9f7a4e"),
                            Color = "Trắng",
                            ImageUrl = "",
                            Price = 99000m,
                            Size = "L",
                            Stock = 100
                        });
                });

            modelBuilder.Entity("api.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8f5e153-b4b5-4ff4-b319-634ce211f9ca"),
                            Comment = "Áo đẹp lắm",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(622),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("3975f174-2468-4e35-8fc2-11da5346984a"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(628),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("5d4c03c8-40ac-4af3-a1ef-4fcc5017caac"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(633),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("5286b304-0ebb-4e5c-8812-d1e18c0bac4d"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(635),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("9454169e-2209-4548-85db-abf641707ede"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(637),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("2c80b9da-40c9-445f-9ec3-643298d46852"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(640),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("426457ca-07cf-4253-9e93-b019935dcfbf"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(644),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("c203576d-97e6-45e4-be00-7003ebb26d97"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(646),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("6acd78af-1067-44d2-ac56-6c3f05f031d0"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(648),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("4417baae-c61a-4864-b01d-d74f8eb1a26a"),
                            Comment = "Nice",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(651),
                            ProductId = new Guid("e917a7f8-8a12-4df7-bd32-904b2e53b6fa"),
                            Rating = 4
                        });
                });

            modelBuilder.Entity("api.Models.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e4c1467-1426-4b97-902c-bacb85f56cc0"),
                            Address = "Ha Noi",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(144),
                            Email = "jd.shopfashion@gmail.com",
                            FirstName = "",
                            LastName = "",
                            Password = "asdasd123123",
                            Phone = "0123456789",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(147),
                            Username = "jdshop"
                        },
                        new
                        {
                            Id = new Guid("556ee2c5-6eab-4e10-bfa0-8f2f99003ff8"),
                            Address = "Ha Noi",
                            CreatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(171),
                            Email = "jd.shopfashion1@gmail.com",
                            FirstName = "",
                            LastName = "",
                            Password = "asdasd123123",
                            Phone = "0123456789",
                            Role = "User",
                            UpdatedAt = new DateTime(2025, 3, 10, 9, 48, 51, 583, DateTimeKind.Utc).AddTicks(171),
                            Username = "jdshop"
                        });
                });

            modelBuilder.Entity("api.Models.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("api.Models.Cart", b =>
                {
                    b.HasOne("api.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("api.Models.OrderItem", b =>
                {
                    b.HasOne("api.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("api.Models.Payment", b =>
                {
                    b.HasOne("api.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("api.Models.Product", b =>
                {
                    b.HasOne("api.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("api.Models.ProductVariant", b =>
                {
                    b.HasOne("api.Models.Product", null)
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("api.Models.Review", b =>
                {
                    b.HasOne("api.Models.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("api.Models.Wishlist", b =>
                {
                    b.HasOne("api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("api.Models.Product", b =>
                {
                    b.Navigation("ProductVariants");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
